# See: https://mypy.readthedocs.io/en/stable/config_file.html

[mypy]
plugins = pydantic.mypy

# Exclude only directories that match these pattern
exclude = (^|.*/)(tests|dist|test|src/js|src/dart)(/|$)

# These can be overly strict - disabled for now
disable_error_code = import-untyped,assignment,call-overload,misc
enable_error_code = possibly-undefined,explicit-override,redundant-expr,redundant-self,redundant-cast,var-annotated

# Disallow dynamic typing
disallow_any_unimported = False
disallow_any_expr = True
disallow_any_decorated = True
disallow_any_generics = False
disallow_any_explicit = False
disallow_subclassing_any = True
disallow_untyped_decorators = True

# Disallow untyped definitions and calls
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True

# None and optional handling
no_implicit_optional = True

# Configuring warnings
warn_unused_ignores = True
warn_no_return = True
warn_return_any = True
warn_redundant_casts = True

# Misc things
strict_equality = True

[pydantic-mypy]
init_forbid_extra = True
