# Generated by datamodel-codegen from the Outline OpenAPI specification.
#
# Do not edit by hand: run `make schemas` to regenerate from
# https://github.com/outline/openapi/blob/main/spec3.json
#
# ruff: noqa: D205, D400, D404, D415, E501

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AwareDatetime, Field

from outline_client.schemas.base import OutlineBaseModel


class Permission(StrEnum):
    READ = "read"
    READ_WRITE = "read_write"
    ADMIN = "admin"


class TextEditMode(StrEnum):
    """
    The editing mode for text updates to a document. When set to `patch`, the `findText` parameter is required and the existing occurrence of `findText` will be replaced with the value of `text`.
    """

    APPEND = "append"
    PREPEND = "prepend"
    REPLACE = "replace"
    PATCH = "patch"


class AccessRequestStatus(StrEnum):
    """
    The current status of the access request.
    """

    PENDING = "pending"
    APPROVED = "approved"
    DISMISSED = "dismissed"


class Attachment(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the attachment.
    """
    content_type: Annotated[
        str | None, Field(alias="contentType", examples=["image/png"])
    ] = None
    size: str | None = None
    """
    The size of the attachment in bytes. Returned as a string as the value may exceed the safe integer range.
    """
    name: str | None = None
    url: str | None = None
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier for the associated document, if any.
    """
    user_id: Annotated[UUID | None, Field(alias="userId")] = None
    """
    Identifier for the user that created the attachment.
    """


class Pagination(OutlineBaseModel):
    offset: Annotated[float | None, Field(examples=[0])] = None
    limit: Annotated[float | None, Field(examples=[25])] = None


class SortDirection(StrEnum):
    ASC = "ASC"
    DESC = "DESC"


class Sorting(OutlineBaseModel):
    sort: Annotated[str | None, Field(examples=["updatedAt"])] = None
    direction: Annotated[SortDirection | None, Field(examples=["DESC"])] = None


class DocumentFilterField(StrEnum):
    """
    Name of the document field to filter on.
    """

    CREATED_AT = "createdAt"
    UPDATED_AT = "updatedAt"
    PUBLISHED_AT = "publishedAt"
    ARCHIVED_AT = "archivedAt"
    TITLE = "title"
    TEMPLATE_ID = "templateId"
    COLLECTION_ID = "collectionId"
    USER_ID = "userId"
    DOCUMENT_ID = "documentId"
    PARENT_DOCUMENT_ID = "parentDocumentId"


class DocumentFilterOperator(StrEnum):
    """
    Comparison operator to apply. Note that some fields only accept a subset of operators – for example `userId` and `documentId` only support `eq` and `in`.
    """

    EQ = "eq"
    NEQ = "neq"
    LT = "lt"
    LTE = "lte"
    GT = "gt"
    GTE = "gte"
    CONTAINS = "contains"
    STARTS_WITH = "startsWith"
    ENDS_WITH = "endsWith"
    CONTAINS_STRICT = "containsStrict"
    STARTS_WITH_STRICT = "startsWithStrict"
    ENDS_WITH_STRICT = "endsWithStrict"
    IN = "in"
    NOT_IN = "notIn"
    IS_NULL = "isNull"
    IS_NOT_NULL = "isNotNull"


class DocumentFilterCondition(OutlineBaseModel):
    """
    A condition that compares a document field against a value.
    """

    field: DocumentFilterField
    """
    Name of the document field to filter on.
    """
    operator: DocumentFilterOperator
    """
    Comparison operator to apply. Note that some fields only accept a subset of operators – for example `userId` and `documentId` only support `eq` and `in`.
    """
    value: Any | None = None
    """
    Value to compare against. May be a string, number, boolean or array of these depending on the field and operator. Date fields accept an ISO 8601 date or an ISO 8601 duration (relative to now). Omit for `isNull` and `isNotNull`.
    """


class DocumentFilterGroupOperator(StrEnum):
    AND = "AND"
    OR = "OR"


class DocumentsDeletedFilterField(StrEnum):
    """
    Name of the field to filter on.
    """

    DELETED_AT = "deletedAt"
    DELETED_BY_ID = "deletedById"


class DocumentsDeletedFilterOperator(StrEnum):
    """
    Comparison operator to apply. `deletedById` only supports `eq` and `in`.
    """

    EQ = "eq"
    NEQ = "neq"
    LT = "lt"
    LTE = "lte"
    GT = "gt"
    GTE = "gte"
    IN = "in"
    NOT_IN = "notIn"
    IS_NULL = "isNull"
    IS_NOT_NULL = "isNotNull"


class DocumentsDeletedFilterCondition(OutlineBaseModel):
    """
    A condition that compares a deleted-document field against a value.
    """

    field: DocumentsDeletedFilterField
    """
    Name of the field to filter on.
    """
    operator: DocumentsDeletedFilterOperator
    """
    Comparison operator to apply. `deletedById` only supports `eq` and `in`.
    """
    value: Any | None = None
    """
    Value to compare against. `deletedAt` accepts an ISO 8601 date or an ISO 8601 duration (relative to now); `deletedById` accepts a user UUID (or an array of UUIDs with `in`/`notIn`). Omit for `isNull` and `isNotNull`.
    """


class DocumentsDeletedFilterGroupOperator(StrEnum):
    AND = "AND"
    OR = "OR"


class CollectionFilterField(StrEnum):
    """
    Name of the collection field to filter on.
    """

    NAME = "name"
    CREATED_AT = "createdAt"
    UPDATED_AT = "updatedAt"
    ARCHIVED_AT = "archivedAt"
    CREATED_BY_ID = "createdById"
    PERMISSION = "permission"


class CollectionFilterOperator(StrEnum):
    """
    Comparison operator to apply. Note that some fields only accept a subset of operators – for example `permission` only supports `eq`, `neq`, `in`, `notIn`, `isNull` and `isNotNull`.
    """

    EQ = "eq"
    NEQ = "neq"
    LT = "lt"
    LTE = "lte"
    GT = "gt"
    GTE = "gte"
    CONTAINS = "contains"
    STARTS_WITH = "startsWith"
    ENDS_WITH = "endsWith"
    CONTAINS_STRICT = "containsStrict"
    STARTS_WITH_STRICT = "startsWithStrict"
    ENDS_WITH_STRICT = "endsWithStrict"
    IN = "in"
    NOT_IN = "notIn"
    IS_NULL = "isNull"
    IS_NOT_NULL = "isNotNull"


class CollectionFilterCondition(OutlineBaseModel):
    """
    A condition that compares a collection field against a value.
    """

    field: CollectionFilterField
    """
    Name of the collection field to filter on.
    """
    operator: CollectionFilterOperator
    """
    Comparison operator to apply. Note that some fields only accept a subset of operators – for example `permission` only supports `eq`, `neq`, `in`, `notIn`, `isNull` and `isNotNull`.
    """
    value: Any | None = None
    """
    Value to compare against. May be a string, boolean or array of these depending on the field and operator. Date fields accept an ISO 8601 date or an ISO 8601 duration (relative to now). `permission` accepts a `Permission` enum value (or an array with `in`/`notIn`). Omit for `isNull` and `isNotNull`.
    """


class CollectionFilterGroupOperator(StrEnum):
    AND = "AND"
    OR = "OR"


class UserFilterField(StrEnum):
    """
    Name of the user field to filter on.
    """

    ID = "id"
    NAME = "name"
    EMAIL = "email"
    ROLE = "role"
    CREATED_AT = "createdAt"
    UPDATED_AT = "updatedAt"
    LAST_ACTIVE_AT = "lastActiveAt"
    SUSPENDED_AT = "suspendedAt"


class UserFilterOperator(StrEnum):
    """
    Comparison operator to apply. Note that some fields only accept a subset of operators – `id` and `role` only support `eq`, `neq`, `in` and `notIn`.
    """

    EQ = "eq"
    NEQ = "neq"
    LT = "lt"
    LTE = "lte"
    GT = "gt"
    GTE = "gte"
    CONTAINS = "contains"
    STARTS_WITH = "startsWith"
    ENDS_WITH = "endsWith"
    CONTAINS_STRICT = "containsStrict"
    STARTS_WITH_STRICT = "startsWithStrict"
    ENDS_WITH_STRICT = "endsWithStrict"
    IN = "in"
    NOT_IN = "notIn"
    IS_NULL = "isNull"
    IS_NOT_NULL = "isNotNull"


class UserFilterCondition(OutlineBaseModel):
    """
    A condition that compares a user field against a value.
    """

    field: UserFilterField
    """
    Name of the user field to filter on.
    """
    operator: UserFilterOperator
    """
    Comparison operator to apply. Note that some fields only accept a subset of operators – `id` and `role` only support `eq`, `neq`, `in` and `notIn`.
    """
    value: Any | None = None
    """
    Value to compare against. May be a string, number, boolean or array of these depending on the field and operator. Date fields accept an ISO 8601 date or an ISO 8601 duration (relative to now). `role` accepts one of the values in `UserRole`. Omit for `isNull` and `isNotNull`.
    """


class UserFilterGroupOperator(StrEnum):
    AND = "AND"
    OR = "OR"


class NavigationNode(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the document.
    """
    title: str | None = None
    url: str | None = None
    children: list[NavigationNode] | None = None


class CollectionSortDirection(StrEnum):
    ASC = "asc"
    DESC = "desc"


class CollectionSort(OutlineBaseModel):
    """
    The sort of documents in the collection. Note that not all API responses respect this and it is left as a frontend concern to implement.
    """

    field: str | None = None
    direction: CollectionSortDirection | None = None


class CollectionSourceMetadata(OutlineBaseModel):
    """
    Metadata about the external source this collection was imported from, if any.
    """

    external_id: Annotated[str | None, Field(alias="externalId")] = None
    external_name: Annotated[str | None, Field(alias="externalName")] = None
    created_by_name: Annotated[str | None, Field(alias="createdByName")] = None


class DataAttributeDataType(StrEnum):
    """
    The data type of the attribute value.
    """

    STRING = "string"
    NUMBER = "number"
    BOOLEAN = "boolean"
    LIST = "list"


class DataAttributeOption(OutlineBaseModel):
    value: str | None = None
    """
    The label/value of the option.
    """
    color: str | None = None
    """
    Optional color for the option.
    """


class DataAttributeOptions(OutlineBaseModel):
    """
    Additional options for certain data attribute types.
    """

    icon: str | None = None
    """
    An icon representing the data attribute from the outline-icons package.
    """
    options: list[DataAttributeOption] | None = None
    """
    Valid options for list data type.
    """


class DocumentDataAttribute(OutlineBaseModel):
    data_attribute_id: Annotated[UUID | None, Field(alias="dataAttributeId")] = None
    """
    Unique identifier for the associated data attribute.
    """
    value: Annotated[str | bool | float | None, Field(examples=["In Progress"])] = None
    """
    The value of the data attribute for this document.
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    The date and time that this object attribute was last changed
    """


class DocumentTasks(OutlineBaseModel):
    """
    Task completion counts for the document.
    """

    completed: float | None = None
    total: float | None = None


class DocumentHeadingPrefix(StrEnum):
    """
    Numbering style applied to the document's headings when rendered.
    """

    NONE = "none"
    NUMERIC = "numeric"
    ALPHANUMERIC = "alphanumeric"
    OUTLINE = "outline"


class DocumentPreferences(OutlineBaseModel):
    """
    Document-level display preferences.
    """

    heading_prefix: Annotated[
        DocumentHeadingPrefix | None, Field(alias="headingPrefix")
    ] = None
    """
    Numbering style applied to the document's headings when rendered.
    """


class DocumentInsightPeriod(StrEnum):
    """
    The length of time the rollup covers. Daily rollups are stored for recent activity, older rollups are aggregated into weekly buckets.
    """

    DAY = "day"
    WEEK = "week"


class DocumentInsight(OutlineBaseModel):
    """
    A rollup of activity counts for a document over a daily or weekly period.
    """

    date: date_aliased | None = None
    """
    The UTC day the rollup represents. For weekly rollups this is the first day (Monday) of the week.
    """
    period: DocumentInsightPeriod | None = None
    """
    The length of time the rollup covers. Daily rollups are stored for recent activity, older rollups are aggregated into weekly buckets.
    """
    view_count: Annotated[int | None, Field(alias="viewCount")] = None
    """
    Total number of document views on this day.
    """
    viewer_count: Annotated[int | None, Field(alias="viewerCount")] = None
    """
    Number of unique viewers on this day.
    """
    comment_count: Annotated[int | None, Field(alias="commentCount")] = None
    """
    Total comments made on this day.
    """
    reaction_count: Annotated[int | None, Field(alias="reactionCount")] = None
    """
    Total reactions added on this day.
    """
    revision_count: Annotated[int | None, Field(alias="revisionCount")] = None
    """
    Number of document revisions on this day.
    """
    editor_count: Annotated[int | None, Field(alias="editorCount")] = None
    """
    Number of unique editors on this day.
    """


class EventAuthType(StrEnum):
    """
    The authentication method used to perform the action.
    """

    API = "api"
    APP = "app"
    MCP = "mcp"
    OAUTH = "oauth"


class Error(OutlineBaseModel):
    ok: Annotated[bool | None, Field(examples=[False])] = None
    error: str | None = None
    message: str | None = None
    status: float | None = None
    data: dict[str, Any] | None = None


class FileOperationType(StrEnum):
    """
    The type of file operation.
    """

    IMPORT = "import"
    EXPORT = "export"


class FileOperationState(StrEnum):
    """
    The state of the file operation.
    """

    CREATING = "creating"
    UPLOADING = "uploading"
    COMPLETE = "complete"
    ERROR = "error"
    EXPIRED = "expired"


class Group(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    name: Annotated[str | None, Field(examples=["Engineering"])] = None
    """
    The name of this group.
    """
    description: str | None = None
    """
    A short description of this group.
    """
    external_id: Annotated[str | None, Field(alias="externalId")] = None
    """
    An identifier for this group in an external system, if linked.
    """
    disable_mentions: Annotated[bool | None, Field(alias="disableMentions")] = None
    """
    Whether mentioning this group is disabled.
    """
    external_group: Annotated[dict[str, Any] | None, Field(alias="externalGroup")] = (
        None
    )
    """
    Details of the linked external group, if any.
    """
    member_count: Annotated[float | None, Field(alias="memberCount", examples=[11])] = (
        None
    )
    """
    The number of users that are members of the group
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    The date and time that this object was created
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    The date and time that this object was last changed
    """


class OAuthClientType(StrEnum):
    """
    The type of the OAuth client.
    """

    PUBLIC = "public"
    CONFIDENTIAL = "confidential"


class OAuthClient(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    name: Annotated[str | None, Field(examples=["Acme Inc"])] = None
    """
    The name of this OAuth client.
    """
    description: Annotated[
        str | None, Field(examples=["Integrate Acme Inc's services into Outline."])
    ] = None
    """
    A short description of this OAuth client.
    """
    developer_name: Annotated[
        str | None, Field(alias="developerName", examples=["Acme Inc"])
    ] = None
    """
    The name of the developer who created this OAuth client.
    """
    developer_url: Annotated[
        str | None, Field(alias="developerUrl", examples=["https://example.com"])
    ] = None
    """
    The URL of the developer who created this OAuth client.
    """
    avatar_url: Annotated[str | None, Field(alias="avatarUrl")] = None
    """
    A URL pointing to an image representing the OAuth client.
    """
    client_id: Annotated[
        str | None, Field(alias="clientId", examples=["2bquf8avrpdv31par42a"])
    ] = None
    """
    The client ID for the OAuth client.
    """
    client_secret: Annotated[
        str | None, Field(alias="clientSecret", examples=["ol_sk_rapdv31..."])
    ] = None
    """
    The client secret for the OAuth client. Only returned when the request is authenticated with a credential whose scope permits managing OAuth clients.
    """
    client_type: Annotated[OAuthClientType | None, Field(alias="clientType")] = None
    """
    The type of the OAuth client.
    """
    redirect_uris: Annotated[
        list[str] | None,
        Field(alias="redirectUris", examples=[["https://example.com/callback"]]),
    ] = None
    """
    The redirect URIs for the OAuth client.
    """
    published: Annotated[bool | None, Field(examples=[True])] = None
    """
    Whether the OAuth client is available to other workspaces.
    """
    last_active_at: Annotated[AwareDatetime | None, Field(alias="lastActiveAt")] = None
    """
    Date and time when this OAuth client was last used.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    Date and time when this OAuth client was created
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    Date and time when this OAuth client was updated
    """


class OAuthClientSummary(OutlineBaseModel):
    """
    A reduced, public representation of the associated OAuth client.
    """

    name: str | None = None
    description: str | None = None
    developer_name: Annotated[str | None, Field(alias="developerName")] = None
    developer_url: Annotated[str | None, Field(alias="developerUrl")] = None
    avatar_url: Annotated[str | None, Field(alias="avatarUrl")] = None
    client_id: Annotated[str | None, Field(alias="clientId")] = None
    published: bool | None = None


class OAuthAuthentication(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    oauth_client_id: Annotated[UUID | None, Field(alias="oauthClientId")] = None
    """
    Identifier for the associated OAuthClient.
    """
    oauth_client: Annotated[OAuthClientSummary | None, Field(alias="oauthClient")] = (
        None
    )
    """
    A reduced, public representation of the associated OAuth client.
    """
    user_id: Annotated[UUID | None, Field(alias="userId")] = None
    """
    Identifier for the associated User.
    """
    scope: list[str] | None = None
    last_active_at: Annotated[AwareDatetime | None, Field(alias="lastActiveAt")] = None
    """
    Date and time when this authentication was last used
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    Date and time when this authentication was created
    """


class RevisionAuthType(StrEnum):
    """
    The authentication method used to create the revision.
    """

    API = "api"
    APP = "app"
    MCP = "mcp"
    OAUTH = "oauth"


class RevisionSourceMetadata(OutlineBaseModel):
    """
    Metadata about how the revision was created, if any.
    """

    auth_type: Annotated[RevisionAuthType | None, Field(alias="authType")] = None
    """
    The authentication method used to create the revision.
    """


class Star(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    index: str | None = None
    """
    Index of the star in the list of stars.
    """
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Unique identifier for the starred document.
    """
    collection_id: Annotated[UUID | None, Field(alias="collectionId")] = None
    """
    Unique identifier for the starred collection.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    Date and time when this star was created
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    Date and time when this star was last changed
    """


class UserRole(StrEnum):
    ADMIN = "admin"
    MEMBER = "member"
    VIEWER = "viewer"
    GUEST = "guest"


class CollectionStatus(StrEnum):
    ARCHIVED = "archived"


class Membership(OutlineBaseModel):
    id: str | None = None
    """
    Unique identifier for the object.
    """
    user_id: Annotated[UUID | None, Field(alias="userId")] = None
    """
    Identifier for the associated user.
    """
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier for the associated document, if any.
    """
    collection_id: Annotated[UUID | None, Field(alias="collectionId")] = None
    """
    Identifier for the associated collection, if any.
    """
    permission: Permission | None = None
    created_by_id: Annotated[UUID | None, Field(alias="createdById")] = None
    """
    Identifier for the user who created this membership.
    """
    source_id: Annotated[UUID | None, Field(alias="sourceId")] = None
    """
    Identifier for the membership this one was inherited from, if any.
    """
    index: str | None = None
    """
    The position of the collection in the user's sidebar.
    """


class SearchResultSource(StrEnum):
    """
    The source of the query
    """

    API = "api"
    APP = "app"
    MCP = "mcp"


class SearchResult(OutlineBaseModel):
    id: UUID | None = None
    query: Annotated[str | None, Field(examples=["What is our hiring policy?"])] = None
    """
    The user-provided search query
    """
    answer: Annotated[
        str | None, Field(examples=["Our hiring policy can be summarized as…"])
    ] = None
    """
    An answer to the query, if possible
    """
    source: Annotated[SearchResultSource | None, Field(examples=["app"])] = None
    """
    The source of the query
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    The date and time that this object was created
    """


class GroupPermission(StrEnum):
    """
    A member's role within a group.
    """

    MEMBER = "member"
    ADMIN = "admin"


class GroupMembership(OutlineBaseModel):
    id: str | None = None
    """
    Unique identifier for the object.
    """
    group_id: Annotated[UUID | None, Field(alias="groupId")] = None
    """
    Identifier for the associated group.
    """
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier for the associated document, if any.
    """
    collection_id: Annotated[UUID | None, Field(alias="collectionId")] = None
    """
    Identifier for the associated collection, if any.
    """
    permission: GroupPermission | None = None
    source_id: Annotated[UUID | None, Field(alias="sourceId")] = None
    """
    Identifier for the membership this one was inherited from, if any.
    """


class CollectionGroupMembership(OutlineBaseModel):
    id: str | None = None
    """
    Unique identifier for the object.
    """
    group_id: Annotated[UUID | None, Field(alias="groupId")] = None
    """
    Identifier for the associated group.
    """
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier for the associated document, if any.
    """
    collection_id: Annotated[UUID | None, Field(alias="collectionId")] = None
    """
    Identifier for the associated collection, if any.
    """
    permission: Permission | None = None
    source_id: Annotated[UUID | None, Field(alias="sourceId")] = None
    """
    Identifier for the membership this one was inherited from, if any.
    """


class ApiKey(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    name: str | None = None
    """
    A user provided name for the API key.
    """
    scope: list[str] | None = None
    """
    An optional list of scopes that restrict which endpoints the key can access. When `null` the key has access to all endpoints available to the user.
    """
    last4: str | None = None
    """
    The last four characters of the key, used to help identify it.
    """
    value: str | None = None
    """
    The full secret value of the key. Only returned once, in the response to `apiKeys.create`.
    """
    expires_at: Annotated[AwareDatetime | None, Field(alias="expiresAt")] = None
    """
    Date and time when this key expires, if ever.
    """
    last_active_at: Annotated[AwareDatetime | None, Field(alias="lastActiveAt")] = None
    """
    Date and time when this key was last used.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    Date and time when this key was created.
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    Date and time when this key was last updated.
    """


class Pin(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier for the pinned document.
    """
    collection_id: Annotated[UUID | None, Field(alias="collectionId")] = None
    """
    Identifier for the collection the document is pinned to. When `null` the document is pinned to the home screen.
    """
    index: str | None = None
    """
    The position of the pin, used for ordering.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    Date and time when this pin was created.
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    Date and time when this pin was last updated.
    """


class Subscription(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    user_id: Annotated[UUID | None, Field(alias="userId")] = None
    """
    Identifier for the subscribed user.
    """
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier for the subscribed document, if any.
    """
    collection_id: Annotated[UUID | None, Field(alias="collectionId")] = None
    """
    Identifier for the subscribed collection, if any.
    """
    event: Annotated[str | None, Field(examples=["documents"])] = None
    """
    The type of event that is subscribed to.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    Date and time when this subscription was created.
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    Date and time when this subscription was last updated.
    """


class Reaction(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    emoji: str | None = None
    """
    The native emoji that was reacted with.
    """
    comment_id: Annotated[UUID | None, Field(alias="commentId")] = None
    """
    Identifier for the comment this reaction belongs to.
    """
    user_id: Annotated[UUID | None, Field(alias="userId")] = None
    """
    Identifier for the user that added the reaction.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    Date and time when this reaction was created.
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    Date and time when this reaction was last updated.
    """


class DataAttribute(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    name: Annotated[str | None, Field(examples=["AccessRequestStatus"])] = None
    """
    The name of this data attribute.
    """
    description: Annotated[
        str | None, Field(examples=["The current status of the document."])
    ] = None
    """
    A description of the data attribute.
    """
    data_type: Annotated[DataAttributeDataType | None, Field(alias="dataType")] = None
    options: DataAttributeOptions | None = None
    pinned: bool | None = False
    """
    Whether this data attribute is pinned to the top of documents.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    The date and time that this object was created
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    The date and time that this object was last changed
    """
    deleted_at: Annotated[AwareDatetime | None, Field(alias="deletedAt")] = None
    """
    The date and time that this object was deleted
    """


class Team(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    name: str | None = None
    """
    The name of this workspace, it is usually auto-generated when the first SSO connection is made but can be changed if necessary.
    """
    description: str | None = None
    """
    A short description of this workspace.
    """
    avatar_url: Annotated[str | None, Field(alias="avatarUrl")] = None
    """
    The URL for the image associated with this workspace, it will be displayed in the workspace switcher and in the top left of the knowledge base along with the name.
    """
    sharing: bool | None = None
    """
    Whether this workspace has share links globally enabled. If this value is false then all sharing UI and APIs are disabled.
    """
    default_collection_id: Annotated[
        UUID | None, Field(alias="defaultCollectionId")
    ] = None
    """
    If set then the referenced collection is where users will be redirected to after signing in instead of the Home screen
    """
    default_user_role: Annotated[UserRole | None, Field(alias="defaultUserRole")] = None
    member_collection_create: Annotated[
        bool | None, Field(alias="memberCollectionCreate")
    ] = None
    """
    Whether members are allowed to create new collections. If false then only admins can create collections.
    """
    member_team_create: Annotated[bool | None, Field(alias="memberTeamCreate")] = None
    """
    Whether members are allowed to create new groups. If false then only admins can create groups.
    """
    document_embeds: Annotated[bool | None, Field(alias="documentEmbeds")] = None
    """
    Whether this workspace has embeds in documents globally enabled. It can be disabled to reduce potential data leakage to third parties.
    """
    invite_required: Annotated[bool | None, Field(alias="inviteRequired")] = None
    """
    Whether an invite is required to join this workspace, if false users may join with a linked SSO provider.
    """
    allowed_domains: Annotated[list[str] | None, Field(alias="allowedDomains")] = None
    guest_signin: Annotated[bool | None, Field(alias="guestSignin")] = None
    """
    Whether this workspace has guest signin enabled. Guests can signin with an email address and are not required to have a Google Workspace/Slack SSO account once invited.
    """
    subdomain: str | None = None
    """
    Represents the subdomain at which this workspace's knowledge base can be accessed.
    """
    domain: str | None = None
    """
    The custom domain configured for this workspace, if any.
    """
    url: str | None = None
    """
    The fully qualified URL at which this workspace's knowledge base can be accessed.
    """
    passkeys_enabled: Annotated[bool | None, Field(alias="passkeysEnabled")] = None
    """
    Whether passkey authentication is enabled for this workspace.
    """
    preferences: dict[str, Any] | None = None
    """
    Workspace-level preference flags.
    """
    guidance_mcp: Annotated[str | None, Field(alias="guidanceMCP")] = None
    """
    Guidance text provided to MCP integrations.
    """


class User(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    name: Annotated[str | None, Field(examples=["Jane Doe"])] = None
    """
    The name of this user, it is migrated from Slack or Google Workspace when the SSO connection is made but can be changed if necessary.
    """
    avatar_url: Annotated[str | None, Field(alias="avatarUrl")] = None
    """
    The URL for the image associated with this user, it will be displayed in the application UI and email notifications.
    """
    color: str | None = None
    """
    A color representing the user, used in the UI for avatars without an image.
    """
    email: str | None = None
    """
    The email associated with this user, it is migrated from Slack or Google Workspace when the SSO connection is made but can be changed if necessary.
    """
    role: UserRole | None = None
    is_suspended: Annotated[bool | None, Field(alias="isSuspended")] = None
    """
    Whether this user has been suspended.
    """
    last_active_at: Annotated[AwareDatetime | None, Field(alias="lastActiveAt")] = None
    """
    The last time this user made an API request, this value is updated at most every 5 minutes.
    """
    timezone: str | None = None
    """
    The timezone this user has registered.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    The date and time that this user first signed in or was invited as a guest.
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    The date and time that this user was last updated.
    """
    deleted_at: Annotated[AwareDatetime | None, Field(alias="deletedAt")] = None
    """
    The date and time that this user was deleted, if applicable.
    """
    invited_by: Annotated[User | None, Field(alias="invitedBy")] = None
    """
    The user that invited this user, if they were invited. Only included in responses to admin users.
    """


class Invite(OutlineBaseModel):
    name: str | None = None
    """
    The full name of the user being invited
    """
    email: str | None = None
    """
    The email address to invite
    """
    role: UserRole | None = None


class Policy(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object this policy references.
    """
    abilities: Annotated[
        dict[str, list[str] | bool] | None,
        Field(examples=[{"read": True, "update": True, "delete": False}]),
    ] = None
    """
    The abilities that are allowed by this policy, if an array is returned then the individual ID's in the array represent the memberships that grant the ability.
    """


class Template(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    url: str | None = None
    """
    A URL path to access the template.
    """
    url_id: Annotated[str | None, Field(alias="urlId")] = None
    """
    A short unique identifier for the template used in URLs.
    """
    title: str | None = None
    """
    The title of the template.
    """
    data: dict[str, Any] | None = None
    """
    The body of the template as a Prosemirror document.
    """
    icon: str | None = None
    """
    An emoji to use as the template icon.
    """
    color: str | None = None
    """
    The color of the template icon in hex format.
    """
    full_width: Annotated[bool | None, Field(alias="fullWidth")] = None
    """
    Whether the template should be displayed full width.
    """
    collection_id: Annotated[UUID | None, Field(alias="collectionId")] = None
    """
    Identifier for the associated collection, if any.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    The date and time that the template was created.
    """
    created_by: Annotated[User | None, Field(alias="createdBy")] = None
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    The date and time that the template was last changed.
    """
    updated_by: Annotated[User | None, Field(alias="updatedBy")] = None
    deleted_at: Annotated[AwareDatetime | None, Field(alias="deletedAt")] = None
    """
    The date and time that the template was deleted.
    """
    published_at: Annotated[AwareDatetime | None, Field(alias="publishedAt")] = None
    """
    The date and time that the template was published.
    """


class WebhookSubscription(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the webhook subscription.
    """
    name: Annotated[
        str | None, Field(examples=["Production webhook"], max_length=255)
    ] = None
    """
    The descriptive name of the webhook subscription.
    """
    url: Annotated[
        str | None, Field(examples=["https://example.com/webhooks/outline"])
    ] = None
    """
    The URL that receives webhook requests.
    """
    secret: Annotated[str | None, Field(examples=["ol_whs_1234567890abcdef"])] = None
    """
    The optional secret used to sign webhook requests.
    """
    events: Annotated[
        list[str] | None, Field(examples=[["documents.create", "documents.update"]])
    ] = None
    """
    Event names or namespaces that trigger the webhook. `*` subscribes to all events.
    """
    enabled: bool | None = None
    """
    Whether the webhook subscription is enabled.
    """
    created_by: Annotated[User | None, Field(alias="createdBy")] = None
    """
    The user who created the webhook subscription, if available.
    """
    created_by_id: Annotated[UUID | None, Field(alias="createdById")] = None
    """
    Identifier for the user who created the webhook subscription.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    The date and time that the webhook subscription was created.
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    The date and time that the webhook subscription was last changed.
    """


class View(OutlineBaseModel):
    id: str | None = None
    """
    Unique identifier for the object.
    """
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier for the associated document.
    """
    first_viewed_at: Annotated[AwareDatetime | None, Field(alias="firstViewedAt")] = (
        None
    )
    """
    When the document was first viewed by the user
    """
    last_viewed_at: Annotated[AwareDatetime | None, Field(alias="lastViewedAt")] = None
    """
    When the document was last viewed by the user
    """
    count: Annotated[float | None, Field(examples=[22])] = None
    """
    The number of times the user has viewed the document.
    """
    user_id: Annotated[UUID | None, Field(alias="userId")] = None
    """
    Identifier of the user who viewed the document.
    """
    user: User | None = None


class Notification(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    event: str | None = None
    """
    The type of event that triggered the notification.
    """
    user_id: Annotated[UUID | None, Field(alias="userId")] = None
    """
    Identifier for the user the notification belongs to.
    """
    actor_id: Annotated[UUID | None, Field(alias="actorId")] = None
    """
    Identifier for the user that triggered the notification, if any.
    """
    actor: User | None = None
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier for the associated document, if any.
    """
    collection_id: Annotated[UUID | None, Field(alias="collectionId")] = None
    """
    Identifier for the associated collection, if any.
    """
    comment_id: Annotated[UUID | None, Field(alias="commentId")] = None
    """
    Identifier for the associated comment, if any.
    """
    revision_id: Annotated[UUID | None, Field(alias="revisionId")] = None
    """
    Identifier for the associated revision, if any.
    """
    viewed_at: Annotated[AwareDatetime | None, Field(alias="viewedAt")] = None
    """
    Date and time the notification was marked as viewed, if it has been.
    """
    archived_at: Annotated[AwareDatetime | None, Field(alias="archivedAt")] = None
    """
    Date and time the notification was archived, if it has been.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    Date and time when this notification was created.
    """


class AccessRequest(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier for the document this request is for.
    """
    user_id: Annotated[UUID | None, Field(alias="userId")] = None
    """
    Identifier for the user that made the request.
    """
    user: User | None = None
    team_id: Annotated[UUID | None, Field(alias="teamId")] = None
    """
    Identifier for the workspace the request belongs to.
    """
    status: AccessRequestStatus | None = None
    """
    The current status of the access request.
    """
    responder_id: Annotated[UUID | None, Field(alias="responderId")] = None
    """
    Identifier for the user that responded to the request, if any.
    """
    responder: User | None = None
    responded_at: Annotated[AwareDatetime | None, Field(alias="respondedAt")] = None
    """
    The date and time the request was responded to, if any.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    The date and time that this object was created
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    The date and time that this object was last changed
    """


class Auth(OutlineBaseModel):
    user: User | None = None
    team: Team | None = None


class Collection(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    url: str | None = None
    """
    The relative URL path at which the collection can be accessed.
    """
    url_id: Annotated[str | None, Field(alias="urlId", examples=["hDYep1TPAM"])] = None
    """
    A short unique identifier that can be used to identify the collection instead of the UUID.
    """
    name: Annotated[str | None, Field(examples=["Human Resources"])] = None
    """
    The name of the collection.
    """
    description: Annotated[str | None, Field(examples=[""])] = None
    """
    A description of the collection, may contain markdown formatting
    """
    data: dict[str, Any] | None = None
    """
    The collection description as rich-text JSON, when available.
    """
    sort: CollectionSort | None = None
    """
    The sort of documents in the collection. Note that not all API responses respect this and it is left as a frontend concern to implement.
    """
    index: Annotated[str | None, Field(examples=["P"])] = None
    """
    The position of the collection in the sidebar
    """
    color: Annotated[str | None, Field(examples=["#123123"])] = None
    """
    A color representing the collection, this is used to help make collections more identifiable in the UI. It should be in HEX format including the #
    """
    icon: str | None = None
    """
    A string that represents an icon in the outline-icons package or an emoji
    """
    permission: Permission | None = None
    template_management: Annotated[
        Permission | None, Field(alias="templateManagement")
    ] = None
    sharing: bool | None = False
    """
    Whether public document sharing is enabled in this collection
    """
    commenting: bool | None = None
    """
    Whether commenting is enabled in this collection
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    The date and time that this object was created
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    The date and time that this object was last changed
    """
    deleted_at: Annotated[AwareDatetime | None, Field(alias="deletedAt")] = None
    """
    The date and time that this object was deleted
    """
    archived_at: Annotated[AwareDatetime | None, Field(alias="archivedAt")] = None
    """
    The date and time that this object was archived
    """
    archived_by: Annotated[User | None, Field(alias="archivedBy")] = None
    source_metadata: Annotated[
        CollectionSourceMetadata | None, Field(alias="sourceMetadata")
    ] = None
    """
    Metadata about the external source this collection was imported from, if any.
    """


class Comment(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    data: dict[str, Any] | None = None
    """
    The editor data representing this comment.
    """
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier for the document this is related to.
    """
    parent_comment_id: Annotated[UUID | None, Field(alias="parentCommentId")] = None
    """
    Identifier for the comment this is a child of, if any.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    The date and time that this object was created
    """
    created_by: Annotated[User | None, Field(alias="createdBy")] = None
    created_by_id: Annotated[UUID | None, Field(alias="createdById")] = None
    """
    Identifier for the user who created this comment.
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    The date and time that this object was last changed
    """
    resolved_at: Annotated[AwareDatetime | None, Field(alias="resolvedAt")] = None
    """
    The date and time that this comment was resolved, if it has been.
    """
    resolved_by: Annotated[User | None, Field(alias="resolvedBy")] = None
    resolved_by_id: Annotated[UUID | None, Field(alias="resolvedById")] = None
    """
    Identifier for the user who resolved this comment, if any.
    """
    reactions: list[dict[str, Any]] | None = None
    """
    List of emoji reactions on this comment.
    """
    anchor_text: Annotated[str | None, Field(alias="anchorText")] = None
    """
    The document text that the comment is anchored to, only included if includeAnchorText=true.
    """


class Document(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    collection_id: Annotated[UUID | None, Field(alias="collectionId")] = None
    """
    Identifier for the associated collection.
    """
    parent_document_id: Annotated[UUID | None, Field(alias="parentDocumentId")] = None
    """
    Identifier for the document this is a child of, if any.
    """
    title: Annotated[str | None, Field(examples=["Welcome to Acme Inc"])] = None
    """
    The title of the document.
    """
    full_width: Annotated[bool | None, Field(alias="fullWidth")] = None
    """
    Whether this document should be displayed in a full-width view.
    """
    icon: Annotated[str | None, Field(examples=["🎉"])] = None
    """
    An emoji or icon associated with the document.
    """
    color: str | None = None
    """
    The color of the document icon in hex format.
    """
    text: Annotated[str | None, Field(examples=["…"])] = None
    """
    The text content of the document, contains markdown formatting
    """
    data: dict[str, Any] | None = None
    """
    The body of the document as a Prosemirror document, returned in place of text when requested.
    """
    url: str | None = None
    """
    A URL path to access the document.
    """
    url_id: Annotated[str | None, Field(alias="urlId", examples=["hDYep1TPAM"])] = None
    """
    A short unique ID that can be used to identify the document as an alternative to the UUID
    """
    collaborator_ids: Annotated[list[UUID] | None, Field(alias="collaboratorIds")] = (
        None
    )
    """
    Identifiers of users who have edited the document.
    """
    tasks: DocumentTasks | None = None
    """
    Task completion counts for the document.
    """
    template_id: Annotated[UUID | None, Field(alias="templateId")] = None
    """
    Unique identifier for the template this document was created from, if any
    """
    revision: float | None = None
    """
    A number that is auto incrementing with every revision of the document that is saved
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    The date and time that this object was created
    """
    created_by: Annotated[User | None, Field(alias="createdBy")] = None
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    The date and time that this object was last changed
    """
    updated_by: Annotated[User | None, Field(alias="updatedBy")] = None
    published_at: Annotated[AwareDatetime | None, Field(alias="publishedAt")] = None
    """
    The date and time that this object was published
    """
    data_attributes: Annotated[
        list[DocumentDataAttribute] | None, Field(alias="dataAttributes")
    ] = None
    archived_at: Annotated[AwareDatetime | None, Field(alias="archivedAt")] = None
    """
    The date and time that this object was archived
    """
    deleted_at: Annotated[AwareDatetime | None, Field(alias="deletedAt")] = None
    """
    The date and time that this object was deleted
    """
    deleted_by: Annotated[User | None, Field(alias="deletedBy")] = None
    """
    The user who deleted this document, if any. Only present on deleted documents.
    """
    preferences: DocumentPreferences | None = None
    """
    Document-level display preferences.
    """


class Event(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    name: Annotated[str | None, Field(examples=["documents.create"])] = None
    model_id: Annotated[UUID | None, Field(alias="modelId")] = None
    """
    Identifier for the object this event is associated with when it is not one of document, collection, or user.
    """
    user_id: Annotated[UUID | None, Field(alias="userId")] = None
    """
    Identifier for the user associated with the event, if any.
    """
    actor_id: Annotated[UUID | None, Field(alias="actorId")] = None
    """
    The user that performed the action.
    """
    auth_type: Annotated[EventAuthType | None, Field(alias="authType")] = None
    """
    The authentication method used to perform the action.
    """
    actor_ip_address: Annotated[
        str | None, Field(alias="actorIpAddress", examples=["60.169.88.100"])
    ] = None
    """
    The ip address the action was performed from. This field is only returned when the `auditLog` boolean is true.
    """
    collection_id: Annotated[UUID | None, Field(alias="collectionId")] = None
    """
    Identifier for the associated collection, if any
    """
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier for the associated document, if any
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    The date and time that this event was created
    """
    data: Annotated[
        dict[str, Any] | None, Field(examples=[{"name": "Equipment list"}])
    ] = None
    """
    Additional unstructured data associated with the event
    """
    changes: dict[str, Any] | None = None
    """
    The set of changes made by this event. This field is only returned when the `auditLog` boolean is true.
    """
    actor: User | None = None


class FileOperation(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    type: Annotated[FileOperationType | None, Field(examples=["export"])] = None
    """
    The type of file operation.
    """
    format: Annotated[str | None, Field(examples=["outline-markdown"])] = None
    """
    The file format of the resulting file.
    """
    name: str | None = None
    """
    The name of the file operation, derived from the collection name, document title, or file name.
    """
    state: Annotated[FileOperationState | None, Field(examples=["complete"])] = None
    """
    The state of the file operation.
    """
    error: str | None = None
    """
    An error message if the file operation failed.
    """
    size: Annotated[str | None, Field(examples=["2048"])] = None
    """
    The size of the resulting file in bytes. Returned as a string as the value may exceed the safe integer range.
    """
    collection_id: Annotated[UUID | None, Field(alias="collectionId")] = None
    """
    Identifier for the associated collection, if the file operation is scoped to a single collection.
    """
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier for the associated document, if the file operation is scoped to a single document.
    """
    user: User | None = None
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    The date and time that this object was created
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    The date and time that this object was last changed
    """


class Revision(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier for the associated document.
    """
    title: str | None = None
    """
    Title of the document.
    """
    name: str | None = None
    """
    The name of the revision, if any.
    """
    icon: str | None = None
    """
    An emoji or icon associated with the revision.
    """
    color: str | None = None
    """
    The color of the revision icon in hex format.
    """
    collaborators: list[User] | None = None
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    Date and time when this revision was created
    """
    created_by: Annotated[User | None, Field(alias="createdBy")] = None
    created_by_id: Annotated[UUID | None, Field(alias="createdById")] = None
    """
    Identifier for the user who created this revision.
    """
    deleted_at: Annotated[AwareDatetime | None, Field(alias="deletedAt")] = None
    """
    Date and time when this revision was deleted, if applicable.
    """
    source_metadata: Annotated[
        RevisionSourceMetadata | None, Field(alias="sourceMetadata")
    ] = None
    """
    Metadata about how the revision was created, if any.
    """


class RevisionDetail(Revision):
    data: dict[str, Any] | None = None
    """
    The body of the revision as a Prosemirror document.
    """
    text: str | None = None
    """
    Body of the document, may contain markdown formatting
    """


class Share(OutlineBaseModel):
    id: UUID | None = None
    """
    Unique identifier for the object.
    """
    document_title: Annotated[
        str | None, Field(alias="documentTitle", examples=["React best practices"])
    ] = None
    """
    Title of the shared document.
    """
    document_url: Annotated[str | None, Field(alias="documentUrl")] = None
    """
    URL of the original document.
    """
    source_title: Annotated[str | None, Field(alias="sourceTitle")] = None
    """
    Title of the shared document or collection.
    """
    source_path: Annotated[str | None, Field(alias="sourcePath")] = None
    """
    Path of the shared document or collection.
    """
    document_id: Annotated[UUID | None, Field(alias="documentId")] = None
    """
    Identifier of the shared document, if any.
    """
    collection_id: Annotated[UUID | None, Field(alias="collectionId")] = None
    """
    Identifier of the shared collection, if any.
    """
    url_id: Annotated[str | None, Field(alias="urlId")] = None
    """
    Short URL identifier for the share, if set.
    """
    url: str | None = None
    """
    URL of the publicly shared document.
    """
    domain: str | None = None
    """
    Custom domain the share is served on, if any.
    """
    title: Annotated[str | None, Field(max_length=255)] = None
    """
    Override title displayed on the publicly shared page. If not set the source document or collection title is used.
    """
    icon_url: Annotated[str | None, Field(alias="iconUrl")] = None
    """
    URL of an icon displayed on the publicly shared page, overriding the workspace branding.
    """
    published: Annotated[bool | None, Field(examples=[False])] = None
    """
    If true the share can be loaded without a user account.
    """
    include_child_documents: Annotated[
        bool | None, Field(alias="includeChildDocuments", examples=[True])
    ] = None
    """
    If to also give permission to view documents nested beneath this one.
    """
    allow_subscriptions: Annotated[
        bool | None, Field(alias="allowSubscriptions", examples=[True])
    ] = None
    """
    Whether visitors to the public share can subscribe to receive email notifications when the document is updated. Requires SMTP to be configured on the workspace.
    """
    allow_indexing: Annotated[bool | None, Field(alias="allowIndexing")] = None
    """
    Whether the shared page may be indexed by search engines.
    """
    show_last_updated: Annotated[bool | None, Field(alias="showLastUpdated")] = None
    """
    Whether to show the last-updated time on the shared page.
    """
    show_toc: Annotated[bool | None, Field(alias="showTOC")] = None
    """
    Whether to show a table of contents on the shared page.
    """
    views: float | None = None
    """
    The number of times the shared page has been viewed.
    """
    created_at: Annotated[AwareDatetime | None, Field(alias="createdAt")] = None
    """
    Date and time when this share was created
    """
    created_by: Annotated[User | None, Field(alias="createdBy")] = None
    """
    The user that created the share. Only returned to viewers with access to read the share; omitted from responses to unauthenticated viewers of a published share, and when the creating user has been deleted.
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias="updatedAt")] = None
    """
    Date and time when this share was edited
    """
    last_accessed_at: Annotated[AwareDatetime | None, Field(alias="lastAccessedAt")] = (
        None
    )
    """
    Date and time when this share was last viewed. Only returned to workspace admins.
    """


class DocumentFilterGroup(OutlineBaseModel):
    """
    A logical group that combines nested filters with an `AND` or `OR` operator. Groups may themselves contain further groups.
    """

    operator: DocumentFilterGroupOperator
    filters: list[DocumentFilterCondition | DocumentFilterGroup]


class DocumentsDeletedFilterGroup(OutlineBaseModel):
    """
    A logical group that combines nested filters with an `AND` or `OR` operator. Groups may themselves contain further groups.
    """

    operator: DocumentsDeletedFilterGroupOperator
    filters: list[DocumentsDeletedFilterCondition | DocumentsDeletedFilterGroup]


class CollectionFilterGroup(OutlineBaseModel):
    """
    A logical group that combines nested filters with an `AND` or `OR` operator. Groups may themselves contain further groups.
    """

    operator: CollectionFilterGroupOperator
    filters: list[CollectionFilterCondition | CollectionFilterGroup]


class UserFilterGroup(OutlineBaseModel):
    """
    A logical group that combines nested filters with an `AND` or `OR` operator. Groups may themselves contain further groups.
    """

    operator: UserFilterGroupOperator
    filters: list[UserFilterCondition | UserFilterGroup]


NavigationNode.model_rebuild()
User.model_rebuild()
DocumentFilterGroup.model_rebuild()
DocumentsDeletedFilterGroup.model_rebuild()
CollectionFilterGroup.model_rebuild()
UserFilterGroup.model_rebuild()
